# Generated by Django 5.2.10 on 2026-02-22 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', 'Map Image'), ('document', 'Discussion/Risk Table')], max_length=20)),
                ('day', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5')], null=True)),
                ('slug', models.CharField(blank=True, choices=[('short-discussion', 'Short Range Discussion'), ('medium-discussion', 'Medium Range Discussion'), ('medium-risktable', 'Medium Range Risk Table'), ('short-risktable', 'Short Range Risk Table')], max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(max_length=500, upload_to='')),
                ('issue_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasts.forecastcategory')),
            ],
            options={
                'ordering': ['-issue_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('content_type', 'image')), fields=('category', 'day', 'issue_date'), name='unique_image_forecast'), models.UniqueConstraint(condition=models.Q(('content_type', 'document')), fields=('category', 'slug', 'issue_date'), name='unique_document_forecast')],
            },
        ),
    ]
