# Generated by Django 5.2.10 on 2026-02-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('day1', 'Day 1'), ('day2', 'Day 2'), ('day3', 'Day 3')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('map_image', models.ImageField(upload_to='forecasts/maps/')),
                ('discussion_doc', models.FileField(blank=True, upload_to='forecasts/discussions/')),
                ('risk_table_doc', models.FileField(blank=True, upload_to='forecasts/risk_tables/')),
                ('issue_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasts.forecastcategory')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
