# Generated by Django 5.2.10 on 2026-03-08 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='file',
        ),
        migrations.AddField(
            model_name='forecast',
            name='file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='slug',
            field=models.CharField(blank=True, choices=[('short-discussion', 'Short Range Discussion'), ('medium-discussion', 'Medium Range Discussion'), ('medium-risktable', 'Medium Range Risk Table'), ('short-risktable', 'Short Range Risk Table'), ('marine-forecast-daily', 'Marine Forecast Daily'), ('marine-forecast-weekly', 'Marine Forecast Weekly'), ('easfwp-discussions-daily', 'EASFWP Daily Discussion')], max_length=50, null=True),
        ),
    ]
