# Generated by Django 5.2.10 on 2026-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5')]),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='discussion_doc',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='map_image',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='risk_table_doc',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('category', 'day', 'issue_date')},
        ),
    ]
