# Generated by Django 5.2.10 on 2026-02-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
