# Generated by Django 5.2.10 on 2026-03-05 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_announcement_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('warning_type', models.CharField(choices=[('heavy_rainfall', 'Heavy Rainfall Alert'), ('strong_wind', 'Strong Wind Alert'), ('high_tides', 'High Tides'), ('high_temperature', 'High Temperature'), ('high_uv', 'High UV Alert'), ('small_aircraft', 'Small Aircraft Advisory')], max_length=50)),
                ('message', models.TextField()),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = more important')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'warnings',
                'ordering': ['-priority', '-start_at'],
            },
        ),
    ]
