"""
Django settings for kmd_web project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aj9o6jord!qh1t8=6t%*v^1e#gp&(y#f5(6-#s$2wh(hj2!962'
#SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

#DATABASES["default"]["PASSWORD"] = os.getenv("DB_PASSWORD")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#correct DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "172.168.2.103",
    "localhost:5173",
    "127.0.0.1:5173",
    "localhost",
    "127.0.0.1",
    "django"      
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    

    "rest_framework",
    "home.home",
    'corsheaders',
    "products",
    "nwp_models",
    "national_met_services",
    "forecasts",
    "swfp_evaluation",
    "users",
    "pages",
    "wrfapi",
    "news",
    "user_accounts",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'rsmc_config.config.urls'

#SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
#USE_X_FORWARDED_HOST = True

CSRF_TRUSTED_ORIGINS = [
    "http://172.168.2.103",
    "http://localhost:5173",
    "http://127.0.0.1",
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rsmc_config.config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "rsmc_db",
        "USER": "haron",
        "PASSWORD": "haron12345",
        "HOST": "localhost",
        "PORT": "5432",
    }
}
'''for dockerDATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "rsmc_db"),
        "USER": os.getenv("POSTGRES_USER", "haron"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "haron12345"),
        "HOST": os.getenv("POSTGRES_HOST", "postgres"),
        "PORT": "5432",
    }
}'''



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = "/uploads/"
WRF_DATA_DIR = BASE_DIR / "nwp_models_data/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Generated maps directory
GENERATED_MAPS_DIR = BASE_DIR / "generated_maps"

# Auto-create directories if missing
for directory in [WRF_DATA_DIR, GENERATED_MAPS_DIR]:
    directory.mkdir(parents=True, exist_ok=True)
MEDIA_ROOT = "/home/haron/uploads/"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


'''CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        #"LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}'''
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

#CELERY_BROKER_URL = "redis://redis:6379/0"
#CELERY_RESULT_BACKEND = "redis://redis:6379/0"
# Celery
CELERY_BROKER_URL = "redis://localhost:6379/0"
#for dockerCELERY_BROKER_URL = "redis://redis:6379/0"
#forr dockerCELERY_RESULT_BACKEND = "redis://redis:6379/0"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
# Celery Enhancements
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
REDIS_URL="redis://localhost:6379/0"

CELERY_TIMEZONE = "UTC"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_TIME_LIMIT = 1800
CELERY_TASK_SOFT_TIME_LIMIT = 1500
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10
#SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = False   # must be False for React
SESSION_COOKIE_AGE = 600        # 10 minutes
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

#CSRF_COOKIE_SECURE = True #for production
#SESSION_COOKIE_SECURE = True #for production
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"  
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "haron1soy@gmail.com"
EMAIL_HOST_PASSWORD = "ycjywypxextyvhwv"

DEFAULT_FROM_EMAIL = "RSMC <haron1soy@gmail.com>"

SITE_NAME = "RSMC"
CURRENT_YEAR = 2026

FRONTEND_URL = "http://localhost:5173"

# Allow your frontend origin
CORS_ALLOWED_ORIGINS = [
    "http://172.168.2.103",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

#SECURE_SSL_REDIRECT = True #for production
CORS_ALLOW_CREDENTIALS = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "django_errors.log",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}