server {
    listen 80;
    server_name 172.168.2.71 localhost 127.0.0.1;

    client_max_body_size 50M;

    # ─────────────────────────
    # Django Static
    # ─────────────────────────
    location /static/ {
        alias /app/staticfiles/;
        access_log off;
        expires 30d;
    }

    # ─────────────────────────
    # Django Media
    # ─────────────────────────
    location /uploads/ {
        alias /app/uploads/;
        access_log off;
        expires 7d;
    }

    # ─────────────────────────
    # Django Admin
    # ─────────────────────────
    location /admin/ {
        proxy_pass http://django:8000;
        include /etc/nginx/proxy_params;
    }

    # ─────────────────────────
    # Django API
    # ─────────────────────────
    location /api/ {
        proxy_pass http://django:8000;
        include /etc/nginx/proxy_params;

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }

    # ─────────────────────────
    # React frontend
    # ─────────────────────────
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
